### PR TITLE
Add initial functions for parsing results

### PR DESCRIPTION
**Pull request by StatsRhian**
Port initial functions from nhp_output

- `get_results_from_local()`
- `parse_results()`
- `patch_results()`
- `get_trust_sites()`
- `get_available_aggregations()`
- `get_model_run_years()`
- `get_variants()`

Added basic documentation and ported over relevant tests and files.

I chose a few small, simple ones and excluded the Azure functions for now.

Note that there are references in the code base to the `principle` column which won't exist in future model JSON.
Perhaps we should be developing on the output for `v.1.3.` results instead?

### CODE REVIEW

**Comment by StatsRhian** [comment]
Did you remember to /style ?

**Comment by StatsRhian** [comment]
No rush to merge this - maybe we should chat about {nhp.results} early next week @matt-dray ?

**Comment by matt-dray** [comment]
Yes, let's chat Monday. Two quick comments before we talk:

1. Azure-related functions can go in the Azure-specific package I've started putting together this evening, tentatively called {su.azure}. The driving reason for {su.azure} is help us isolate model-run jsons tagged as final', etc. I'd like it to have wider-use for things like nhp_analysis. It already contains the `get_container()` function from nhp_outputs.
2. Yes, I think we have to develop these functions with v1.3 in mind. As per our S3 conversation, I do ideally want <v1.3 supported because otherwise we will have to continue to generate special-case code for schemes that have run on <v1.3 (which is everyone so far, of course).

**Comment by StatsRhian** [comment]
Closing as this code is based on < v2 model

**Pull request closed without merging**
